// @ts-check
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["src/**/*.ts", "test/**/*.ts"],
    rules: {
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  {
    files: ["media/**/*.js"],
    languageOptions: {
      sourceType: "script",
      globals: {
        ...globals.browser,
        acquireVsCodeApi: "readonly",
        DIFF_TOOLS: "writable",
        SLASH_COMMANDS: "writable",
        TOOL_ICONS: "writable",
        activeDelegateCount: "writable",
        addAsideTurn: "writable",
        addErrorNote: "writable",
        addPendingImageFile: "writable",
        addSystemNote: "writable",
        addTurnMeta: "writable",
        addUserTurn: "writable",
        apiKeyCard: "writable",
        apiKeyEnv: "writable",
        apiKeyHint: "writable",
        apiKeyPromptHidden: "writable",
        appendAssistantDelta: "writable",
        applySettings: "writable",
        argsPreview: "writable",
        assistantTurn: "writable",
        attachButton: "writable",
        attachFileInput: "writable",
        attachmentsEl: "writable",
        authHeader: "writable",
        autoApprove: "writable",
        cancelButton: "writable",
        clearStatusCards: "writable",
        closeMenu: "writable",
        commandMenu: "writable",
        commandMenuIndex: "writable",
        commandMenuItems: "writable",
        contextPill: "writable",
        currentModel: "writable",
        delegationEnabled: "writable",
        diffSummary: "writable",
        dismissApiKeyCard: "writable",
        ensureAssistantTurn: "writable",
        escapeHtml: "writable",
        filteredCommands: "writable",
        finishAssistantTurn: "writable",
        formatElapsed: "writable",
        galleryBack: "writable",
        galleryCustom: "writable",
        galleryList: "writable",
        hasApiKey: "writable",
        hideProviderGallery: "writable",
        hideSessionGallery: "writable",
        hideThinkingIndicator: "writable",
        isBusy: "writable",
        isTableRow: "writable",
        isTableSeparator: "writable",
        markToolAutoApproved: "writable",
        memoryEnabled: "writable",
        menu: "writable",
        menuAutoApprove: "writable",
        menuAutoApproveCheck: "writable",
        menuDelegation: "writable",
        menuDelegationCheck: "writable",
        menuMcp: "writable",
        menuMemory: "writable",
        menuMemoryCheck: "writable",
        menuModel: "writable",
        menuProvider: "writable",
        menuReload: "writable",
        menuSessions: "writable",
        menuSettings: "writable",
        menuSkills: "writable",
        menuSkillsCheck: "writable",
        menuToggle: "writable",
        messagesEl: "writable",
        newSessionButton: "writable",
        onMenuClick: "writable",
        parseApiError: "writable",
        pendingAsides: "writable",
        pendingAssistantText: "writable",
        pendingImages: "writable",
        pendingToolCards: "writable",
        promptEl: "writable",
        providerFile: "writable",
        providerGallery: "writable",
        renderApiKeyCard: "writable",
        renderAttachmentsPreview: "writable",
        renderCliMissingCard: "writable",
        renderCommandMenu: "writable",
        renderConfirmRequest: "writable",
        renderDiffBlock: "writable",
        renderFatalError: "writable",
        renderHistory: "writable",
        renderInline: "writable",
        renderMarkdown: "writable",
        renderProviderGallery: "writable",
        renderSessionGallery: "writable",
        renderSetupCard: "writable",
        renderTable: "writable",
        renderTextBlock: "writable",
        renderThinkingText: "writable",
        renderToolCall: "writable",
        resolveAsideTurn: "writable",
        resolveToolResult: "writable",
        runCommand: "writable",
        scrollToBottom: "writable",
        send: "writable",
        sendButton: "writable",
        sessionGallery: "writable",
        sessionGalleryBack: "writable",
        sessionGalleryNew: "writable",
        sessionList: "writable",
        setBusy: "writable",
        setReady: "writable",
        setStatus: "writable",
        shortProviderLabel: "writable",
        showProviderGallery: "writable",
        showSessionGallery: "writable",
        showThinkingIndicator: "writable",
        skillsEnabled: "writable",
        splitTableRow: "writable",
        statusDot: "writable",
        statusText: "writable",
        thinkingEl: "writable",
        thinkingLabel: "writable",
        thinkingStartedAt: "writable",
        thinkingTimer: "writable",
        toolIcon: "writable",
        updateCommandMenu: "writable",
        vscode: "writable",
      },
    },
    rules: {
      "no-redeclare": "off",
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    ignores: ["out/**", "node_modules/**", "*.mjs"],
  }
);
